### ISSUE TITLE
Build inventory python failed

### ISSUE THREAD

**Issue by pasimoes** [oracle/microservices-datadriven#131]
The build process for inventory python is failing to try to apply a required library.

```
#10 29.33 Collecting cryptography<=3.4.7,>=3.2.1 (from oci->-r requirements.txt (line 5))
#10 30.48   Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz (546kB)
#10 31.17     Complete output from command python setup.py egg_info:
#10 31.17     
#10 31.17             =============================DEBUG ASSISTANCE==========================
#10 31.17             If you are seeing an error here please try the following to
#10 31.17             successfully install cryptography:
#10 31.17     
#10 31.17             Upgrade to the latest pip and try again. This will fix errors for most
#10 31.17             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#10 31.17             =============================DEBUG ASSISTANCE==========================
#10 31.17     
#10 31.17     Traceback (most recent call last):
#10 31.17       File "<string>", line 1, in <module>
#10 31.17       File "/tmp/pip-build-3_wb8ir0/cryptography/setup.py", line 14, in <module>
#10 31.17         from setuptools_rust import RustExtension
#10 31.17     ModuleNotFoundError: No module named 'setuptools_rust'
#10 31.17     
#10 31.17     ----------------------------------------
#10 31.51 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3_wb8ir0/cryptography/
------
executor failed running [/bin/sh -c yum install -y python36 &&      yum install -y tar &&      rm -rf /var/cache/yum &&      python3.6 -m pip install -r requirements.txt]: exit code: 1
```

[build-inventory-python.log](https://github.com/oracle/microservices-datadriven/files/6702686/build-inventory-python.log)

**Comment by pasimoes** [comment]
inventory-python Dockerfile updated to include py setuptools. PR submitted.
